spring:
  http:
    log-request-details: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    default-fetch-size: 100
app:
  max-un-finished-count: 5