spring:
  http:
    log-request-details: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    default-fetch-size: 100
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: trace
    io.github.yoshikawaa.sample.todo.domain: trace
app:
  max-un-finished-count: 5