spring:
  http:
    log-request-details: true
mybatis:
  mapper-locations:
  - classpath:/io/github/yoshikawaa/sample/todo/domain/*Mapper.xml
  type-aliases-package: io.github.yoshikawaa.sample.todo.domain
logging:
  level:
    org.springframework.jdbc: trace
    io.github.yoshikawaa.sample.todo.repository: trace
app:
  max-un-finished-count: 5